import AuthProvider from "@/providers/auth-provider";
import "@/styles/index.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className='h-screen overflow-auto flex items-center justify-center'>
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
